version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: tomodachiai-api-dev
    ports:
      - 4000:3000
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    develop:
      watch:
        - path: package.json
          action: rebuild
        - path: bun.lockb
          action: rebuild
        - path: ./src
          target: /app/src
          action: sync
        - path: ./prisma
          target: /app/prisma
          action: sync
  
  db:
    image: postgres:16.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
