version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app
    develop:
      watch:
        - path: package.json
          action: rebuild
        - path: bun.lockb
          action: rebuild
        - path: ./src
          target: /app/src
          action: sync
        - path: ./prisma
          target: /app/prisma
          action: sync
  
  db:
    image: postgres:16.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
