version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tomodachiai-api-prod
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app
  
  db:
    image: postgres:16.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
